#%RAML 0.8
#following https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#9-collections
title: Baker Backoffice Experience API
version: v1
baseUri: http://localhost

/recipes:
  /events:
    get:
      description: Get all possible events from the definition of each recipe
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "value": [
                    {
                      "name": "Carbonara cake",
                      "events": [
                        {
                          "name": "SpaghettiCookedAndDrained",
                          "ingredients": ["Spaghetti", "ResidualWaterInMil"]
                        },
                        {
                          "name": "ChefInfo",
                          "ingredients": ["ChefEmail", "ChefPhoneNumber", "ChefBirthDate"]
                        },
                        {
                          "name": "OvenFailure",
                          "ingredients": ["Reason"]
                        },
                        {
                          "name": "Maybe",
                          "description": "Give your advice",
                          "ingredients": ["AnswerWithYesOrNo"]
                        }
                      ]
                    }
                  ]
                }
/processes:
  get:
    description: Get a list of running processes
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "value" : [
                  {
                    "id": "436fdbcf-2505-4483-adc7-88b8e3b7c370",
                    "recipe": "Carbonara cake",
                    "started": "2017-05-24T15:55:11Z",
                    "events": ["OvenPreheated", "ChefInfo"]
                  },
                  {
                    "id": "e0e86e03-eb25-4ff7-ab48-a7653655e666",
                    "recipe": "Carbonara cake",
                    "started": "2017-04-20T15:53:06Z",
                    "events": ["OvenFailure"]
                  },
                  {
                    "id": "2f144feb-90f5-4936-acab-9199838714ea",
                    "recipe": "Turkey risotto",
                    "started": "2017-01-24T10:43:13Z",
                    "events": ["ChefInfo"]
                  }
                ]
              }
/process/{id}:
  get:
    description: Get a list of ingredients for a process
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "e0e86e03-eb25-4ff7-ab48-a7653655e666",
                "ingredients": [
                  {"name": "OvenTemperature", "value": "285"},
                  {"name": "SpaghettiWeight", "value": "150"},
                  {"name": "ChefName", "value": "John Doe"},
                  {"name": "OrderId", "value": "ABC-341234"}
                ]
              }
  post:
    description: Notify a process that an event happened
    responses:
      204:
